AllCops:
  Exclude:
    - "app/view/**/*"
    - "db/schema.rb"
  TargetRubyVersion: 2.5.1

Documentation:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  Enabled: true
  EnforcedStyleForLeadingUnderscores: optional
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
