default: &default
  adapter: postgresql
  encoding: utf8
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres

development:
  <<: *default
  database: wine_cellar_dev

test:
  <<: *default
  database: wine_cellar_test
  username: <%= ENV['PGUSER'] %>
  password: <%= ENV['PGPASSWORD'] %>
  host: localhost
  pool: 5

production:
  <<: *default
  database: wine_cellar_prod
