default: &default
  adapter: postgresql
  encoding: utf8
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres

development:
  <<: *default
  database: wine_cellar_dev

test:
  <<: *default
  database: wine_cellar_test

production:
  <<: *default
  database: wine_cellar_prod
